###
GET http://127.0.0.1:3002/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsIm5hbWEiOiJ4eHh4IHl5eXkiLCJ1c2VybmFtZSI6ImEiLCJpYXQiOjE2NDc3NzE2OTMsImV4cCI6MTY0Nzc3MTcxOH0.xyi7E4MBCbpEOVDHEU3ULHgAFmhc3mC2r8GhmJzkZZA
###
DELETE  http://127.0.0.1:3002/user/2
###
POST http://127.0.0.1:3002/user/login
Content-Type: application/json

{
    "username":"a",
    "password":"a"
}
###
DELETE  http://127.0.0.1:3002/user/logout
###

GET http://127.0.0.1:3002/ppengesahan
###
GET http://127.0.0.1:3002/mbams
###
GET http://127.0.0.1:3002/mbams/1

###
PATCH  http://127.0.0.1:3002/ppengesahan
Content-Type: application/json

{

    "id": "4",
    "kd_kampung": 1,
    "kd_jbtn": 1,
    "nama": "Kepala Kam",
    "no_sk": "0035_sk/yhk_2124",
    "tgl_sk": "2022-04-16",
    "sts": 1
  }

###
DELETE http://127.0.0.1:3002/ppengesahan
Content-Type: application/json

  {
     "id": 14,
     "kd_jbtn": 1,
     "kd_kampung":1
  }

###
POST http://127.0.0.1:3002/ppengesahan
Content-Type:  application/json

 {
    "kd_kampung": 1,
    "no_sk": "298 TAHUN 2021, Tanggal 15 Oktober 2022",
    "tgl_sk": "2022-10-15",
    "nama": "PUMEKEN HESELO 3",
    "kd_jbtn": 1,
    "sts": 1
  }

###
PATCH  http://127.0.0.1:3002/user/3
Content-Type: application/json
{
    "nama":"xxxxxx",
    "username":"333333333",
    "password":"dasdadxsacsd",
    "nohp":"00780as78780",
    "email":"adasddsad",
    "kd_lvl1": 1,
    "kd_lvl2": 2,
    "kd_kampung": 22,
    "kd_distrik": 11
}


